Repository scaffold-eth/scaffold-eth, pull requests merged in 2021-11, with the labels that each got.

#536 Alchemy RPC setup
  packages/react-app/.sample.env
  packages/react-app/src/App.jsx
  packages/react-app/src/constants.js
Labels: Enhancement, 🧹 Housekeeping, Dependency Update

#540 Challenge 2 hot reload fix
  packages/react-app/package.json
  packages/react-app/src/App.jsx
Labels: 🐞 Bug-fix

#565 Fix: AddressInput backspace issue fix
  packages/react-app/src/components/AddressInput.jsx
Labels: 🐞 Bug-fix, Front-end

#570 issues-568: Clear form on successful submit
  packages/react-app/src/components/Contract/FunctionForm.jsx
Labels: Enhancement, 🏗 Scaffold-eth Core, Front-end

#577 Add error handling to yarn account command
  packages/hardhat/hardhat.config.js
Labels: 🐞 Bug-fix

#576 App.jsx clean up
  packages/react-app/src/App.jsx
  packages/react-app/src/components/Account.jsx
  packages/react-app/src/components/FaucetHint.jsx
  packages/react-app/src/components/NetworkDisplay.jsx
  packages/react-app/src/components/index.js
  packages/react-app/src/helpers/Web3ModalSetup.js
  packages/react-app/src/helpers/index.js
  packages/react-app/src/views/Home.jsx
  packages/react-app/src/views/index.js
Labels: Enhancement, ⛔️ DO NOT MERGE YET, ✅ Approved for Stream

#578 update oz contracts
  packages/hardhat/contracts/YourContract.sol
  packages/hardhat/package.json
  yarn.lock
Labels: Dependency Update

#585 Network Switch component
  packages/react-app/src/App.jsx
  packages/react-app/src/components/NetworkSwitch.jsx
  packages/react-app/src/components/index.js
  packages/react-app/src/hooks/useStaticJsonRPC.js
Labels: Enhancement, 🏗 Scaffold-eth Core, 🧹 Housekeeping, Front-end
