Repository scaffold-eth/scaffold-eth, pull requests merged in 2021-09, with the labels that each got.

#360 Ignore unwanted folders for prettier
  packages/react-app/package.json
Labels: Approved

#367 Update hardhat.config.js
  packages/hardhat/hardhat.config.js
Labels: Approved

#321 Challenge 1: Call out Hardhat bug fix
  packages/hardhat/hardhat.config.js
Labels: bug-fix

#319 eip 1559 : Gas prices calculator
  README.md
  packages/hardhat/package.json
  packages/react-app/package.json
  packages/react-app/src/App.jsx
Labels: enhancement, Approved

#291 added collectors leaderboard
  packages/react-app/src/Leaderboard.js
  packages/react-app/src/LeaderboardCollectors.js
  packages/react-app/src/apollo/queries.js
Labels: enhancement, DO NOT MERGE YET, Approved

#382 update link
  packages/react-app/src/views/Subgraph.jsx
Labels: DO NOT MERGE YET, Approved

#392 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: housekeeping

#404 add transferOwnership to deploy script
  packages/hardhat/deploy/00_deploy_your_contract.js
Labels: documentation, enhancement

#410 Fix the path in README.md
  README.md
Labels: documentation

#437 dependency update
  packages/react-app/package.json
  packages/subgraph/package.json
Labels: dependency-update

#442 Make QuickStart actually Start
  README.md
Labels: documentation

#433 fix(string->bytes32)
  packages/react-app/src/views/CommitReveal.jsx
Labels: bug-fix

#430 update issue-361 with latest master
  .vscode/settings.json
  packages/react-app/package.json
Labels: enhancement, Scaffold-eth Core, DO NOT MERGE YET

#440 Fix/faucet problem#395
  packages/react-app/src/App.jsx
  packages/react-app/src/components/AddressInput.jsx
  packages/react-app/src/components/Contract/FunctionForm.jsx
  packages/react-app/src/components/Contract/index.jsx
  packages/react-app/src/components/Faucet.jsx
  packages/react-app/src/helpers/Transactor.js
Labels: bug-fix

#441 Fix: ens valid name check start with 0x # 420
  packages/react-app/src/components/Address.jsx
Labels: front-end, refactor

#452 upgrade oz to ^4
  packages/hardhat/package.json
  packages/react-app/src/App.jsx
  yarn.lock
Labels: dependency-update
