Repository scaffold-eth/scaffold-eth, pull requests merged in 2022-01, with the labels that each got.

#647 Issue 644 – Add support for displaying Balance in USD or ETH
  ISSUE_TEMPLATE/bug_report.md
  ISSUE_TEMPLATE/feature_request.md
  packages/hardhat/contracts/YourContract.sol
  packages/react-app/src/components/Contract/index.jsx
Labels: Enhancement

#651 Feature: Multi Address Input Component
  packages/react-app/src/components/MultiAddressInput.jsx
  packages/react-app/src/components/index.js
Labels: Front-end, Feature Ideas

#655 Feature: TokenSelect component
  packages/react-app/package.json
  packages/react-app/src/components/TokenSelect.jsx
  packages/react-app/src/components/index.js
Labels: Enhancement, Front-end, To Be Reviewed

#656 Setup default IPFS helper for frontend use cases
  packages/react-app/package.json
  packages/react-app/src/helpers/index.js
  packages/react-app/src/helpers/ipfs.js
Labels: Enhancement, 🧹 Housekeeping, Front-end, Feature Ideas
